davidgranstrom/scnvim

README.md

I added some instructions in the readme to install scnvim using vim's native package management (vim 8.0+) and gently adapted the paragraphs.

add vim native package instructions

---

autoload/scnvim/sclang.vim
rplugin/python3/scnvim/scnvim.py

Problem: The __scnvim_server_start function does not seem to return a value starting
from pynvim 0.4.
Solution: Set the g: variable using the API instead.

Set port using the API

---

sc/Classes/SCNvimDoc/extSCNvim.sc

This is just a quickfix until we have a better parser.

Don't display function signature for ambivalent methods

---

README.md

The readme contains errors in the section on symlinking. This should fix it. 
We need a more consistent way of making sure the symlinks are correct (by somehow verifying that the source path and destination path in the command actually exist before running the symlink command)

Fix linux path errors in Readme

---

indent/supercollider.vim

This PR allows does not indent code for `(` blocks which are used to denote code blocks. This behaviour mimics what sc-ide is doing.
Not sure if this makes the indent behaviour necessarily smart :) but I removed the initial comment

don't indent code blocks

---

autoload/scnvim/lua.vim
autoload/scnvim/sclang.vim
lua/scnvim.lua
lua/udp.lua
plugin/supercollider.vim
sc/Classes/SCNvim.sc
syntax/supercollider.vim

Exit sclang by sending `0.exit` instead of just stopping the job directly. This let's sclang do some internal cleanup, e.g. any current recordings started with `s.record` will be finialized before exiting.
Closes #80

Improve exit handling

---

autoload/health/scnvim.vim
autoload/scnvim/help.vim
autoload/scnvim/util.vim
doc/SCNvim.txt
plugin/supercollider.vim
sc/Classes/SCNvimDoc/extSCNvim.sc

As requested in #85  
This introduces `g:scnvim_scdoc_render_prg` and `g:scnvim_scdoc_render_args` which can be set to use a different executable other than `pandoc` (which is the default).
**Example configuration**
```vim
let g:scnvim_scdoc_render_prg = '/usr/local/bin/html2text'
let g:scnvim_scdoc_render_args = '% -o %'
```
This deprecates `g:scnvim_pandoc_executable` use `g:scnvim_scdoc_render_prg` if a custom path is needed.
Closes #85

Be able to use a custom render program for SCDoc

---

autoload/scnvim/sclang.vim

`thisProcess.recompile` can't be called if there is a parse error in
the class library. Instead send `\x18` like sc-ide does.
Closes #104

Fix class library recompile regression

---

ftdetect/supercollider.vim
syntax/scdoc.vim

This pull request adds syntax colouring for the SuperCollider helpfiles with the suffix `.schelp` from the scvim project github.com/supercollider/scvim
It also adds filetype detection for `.schelp` files and sets the filetype to `scdoc` to trigger the syntax colouring.

[WIP] Schelp syntax colouring

---

doc/SCNvim.txt
syntax/scnvim.vim

This is a pull request to add syntax colouring to the post window. 
The goal of this is to make the post window output easier to read, especially for warning and error messages.
The colouring can be toggled on/off by modifying the global variable `g:scnvim_colour_post_window` and setting it to 1/0. 
Below are examples of it in use:
It is currently a work in progress.

Colour syntax for post window

---

syntax/scnvim.vim

This adds error message color coding to FAIL-messages which are the result of using the UnitTest class and makes it easier to read errors :)

Add error color for unittest FAIL

---

ftdetect/supercollider.vim

Fix for avoiding `nvim`'s default filetype detection for `.sc`-files being of filetype `scala`. Fixes #156

Override nvim default scala filetype detection

---

ftdetect/filetype.lua
ftdetect/supercollider.vim

This PR uses the latest lua API for ftdetect operations. 
There is a conditional to verify if nvim is 0.7 or not to apply the usage

Use lua-ftdetect filetype API if nvim >= 0.7

---

lua/scnvim/udp.lua
scide_scnvim/Classes/SCNvim.sc

This adds another Handler function which interprets luacode sent from sclang. This is mostly useful as an addition to the existing API which would make it easy to control NeoVim from sclang.
```supercollider
SCNvim.luaeval("print(\"sclang says hi\")")
```
A possible usecase for this is a SuperCollider class with some of the common neovim api actions ready to go. I imagine class methods in SC ala `NeoVim*buf_set_lines()` allowing to insert text into neovim buffers from SuperCollider. This interface is outside of the scope of this PR (and possibly scnvim as well?).

feat: add luaeval handler to json communication

---

lua/scnvim/sclang.lua
lua/scnvim/udp.lua
scide_scnvim/Classes/SCNvim.sc

This fixes a long standing issue where lua callbacks could be overwritten depending on order of execution in sclang.

scnvim.eval: Store callbacks in a dictionary instead of a list

---

ftdetect/filetype.lua
ftdetect/supercollider.vim

Integrate with 0.7 release by removing redundant detects.
Add conditional to check for version and lua_filetype variable
0.7 was released earlier today

*.sc, *.scd, *.quark are natively recognized in 0.7

---

syntax/scnvim.vim

This pull requests fixes a number of reg ex issues in the highlighting for the scnvim post window and simplifies the process a bit. 
This is highly opinionated, but I found some of the matches in the first version of this noisy and have opted for simpler matches now where in stead of for example an error mesage only making the ERROR part red, it now makes the whole error message red. The same for the call stacks and other tid bits. This makes it easier to see from a glance if everyting is okay.
It also adds some unit test matching, matches for https://github.com/scztt/Log.quark type messages. 
Here are some examples of what it looks like now:

fix: Simplify scnvim postwindow highlighting

---

lua/scnvim/editor.lua
lua/scnvim/map.lua
test/spec/automated/map_spec.lua

This commit changes the signature for the `map` and `map_expr` helpers in order to support descriptions for keymaps (and perhaps other keymap options in the future).
Here's an example:
```lua
keymaps = {
['<leader>st'] = map('sclang.start', 'n', { desc = 'Start the interpreter' }),
['<CR>'] = map('postwin.toggle', 'n', { desc = 'Toggle post window' }),
}
```
cc: @salkin-mada 
Close #202

Support description for keymaps

---

lua/scnvim/map.lua
test/spec/automated/map_spec.lua

Add default descriptions for keymaps when not specified in keymap configuration:
- `map()`
- `map_expr()`

Add default keymap descriptions

---

syntax/supercollider.vim

fixes, e.g., the highlighting of a variable named `foo_info`.

don't highlight "inf" and "_" within identifiers

---

scide_scnvim/Classes/SCNvim.sc

This fixes https://github.com/davidgranstrom/scnvim/issues/155
It adds a list of characters that need to be escaped from the default arguments of the function signatures that scnvim uses for lua snippets. The list could be expanded to other characters, but I don't immediately see issues with any others than these three `\'"`.

fix: SCNvim producing lua snippets with unescaped characters

---

lua/scnvim/sclang.lua

All paths in the locations array were not considered because the if test always returned true (i.e. the SuperCollider.app had to sit in /Applications). The test should be ~= 0 and thn SuperCollider.app can live inside the subfolder /Applications/SuperCollider.
ref: https://github.com/davidgranstrom/scnvim/issues/200
macOS Mojave, SC 3.13.0, nvim v0.9.5

macos bugfix: allow .app in subfolder

---

lua/scnvim/help.lua

When searching for documentation on a method, the regex doesn't find cases where the line starts with the class name and not just the method name. Also Windows path names are broken coming out of the quickfix window.
This PR should hopefully provide a fix. I added a check for whether Neovim is running on Windows before messing with backslashes, so the path fix shouldn't affect anything on Mac or Linux. Let me know if you need me to split this into a separate commit, I thought I'd just sneak this in since it's just a tiny change.
When you get a chance, can you check this and let me know if anything needs to be cleaned up? I restructured the on_open method and quickfix logic a little so the regex would be easier to parse. I don't think this will break anything, but let me know if I'm …

fix for method documentation search

---

lua/scnvim/signature.lua

Adds functions to `scnvim.signature` to close and toggle the signature hint popup per discussion on #238.

FT: signature hint close and toggle functions

---

scide_scnvim/Classes/SCNvimDoc/extSCNvim.sc

Prevent error on method signature query

---

lua/scnvim/health.lua

The health check file is using deprecated methods. This fixes the health check file to use the latest methods.

Fix health check

---

lua/scnvim/editor.lua
test/spec/automated/editor_spec.lua

Allow sending a block containing a single line with parenthesis, e.g:
```supercollider
(degree: 0).play;
```
Close #249

Send a single line block containing parenthesis
