davidgranstrom/scnvim

autoload/scnvim.vim
A limitation (in contrast to scIDE) is that the opening/closing braces must be on the first column, but it's still an improvement from how it was before.
=> Improve block evaluation

autoload/scnvim.vim
=> Improve block parsing

doc/SCNvim.txt, sc/HelpSource/Classes/SCNvim.schelp
=> Documentation

autoload/scnvim/postwindow.vim, autoload/scnvim/sclang.vim, autoload/scnvim/util.vim
=> Recalculate post window default size

autoload/scnvim/util.vim, sc/Classes/SCNvim.sc, sc/HelpSource/Classes/SCNvim.schelp
=> Fix crash when generating assets

README.md, plugin/supercollider.vim
Closes #17 
TODO: Update example configuration
=> Reset SCNvimEval default hl-group on colorscheme change

autoload/scnvim/sclang.vim, ftplugin/supercollider/supercollider.vim, rplugin/python3/scnvim/scnvim.py
Fixes "no request handler registered for .." bug.
=> Defer startup of remote plugin

README.md, sc/Classes/SCNvim.sc
=> Fix server cpu formatting

README.md
Updated instructions on creating the symbolic and did some formatting in the .MD to make the installation procedure more readable. Also did some formatting (house-cleaning) of the .MD file in general. It is now following markdownlinter rules.
=> notes on symlink

README.md, autoload/scnvim/document.vim, autoload/scnvim/sclang.vim, plugin/supercollider.vim, sc/Classes/Document.sc, sc/Classes/SCNvim.sc
Add partial `Document` support.
Closes #4
=> Be able to use thisProcess.nowExecutingPath

ftplugin/supercollider/supercollider.vim
=> remove tab settings

sc/Classes/Document.sc
=> Add Document.dir

autoload/scnvim/sclang.vim, doc/SCNvim.txt
=> Add a scrollback limit to post window output

autoload/scnvim/sclang.vim
=> Call jobstop() if 0.exit failed

README.md, autoload/scnvim/util.vim, doc/SCNvim.txt, ftplugin/supercollider/mappings.vim, ftplugin/supercollider/supercollider.vim, plugin/supercollider.vim
=> Be able to print function signature on demand

lua/scnvim/install.lua
=> Get plugin root directory for nvim 0.5

lua/scnvim/install.lua
=> Use XDG_DATA_HOME for installation if set

autoload/scnvim/util.vim, doc/SCNvim.txt, ftplugin/supercollider/supercollider.vim, lua/scnvim.lua, lua/scnvim/completion/signature.lua, lua/scnvim/method-signature.lua, plugin/supercollider.vim, scide_scnvim/Classes/SCNvimDoc/extSCNvim.sc
Show method signatures in a floating window instead of the command line area.
This PR does not intend to improve the method signature lookup, that will come in #145 instead.
=> Show method signatures in a floating window

lua/scnvim/help.lua, lua/scnvim/udp.lua, lua/scnvim/utils.lua
=> Expose get_docmap in the API 

lua/scnvim/utils.lua
Hi @davidgranstrom , here's just the commit with the fix for Windows paths. Should I go ahead and close my other request or do you want to continue discussion about how to handle the other commits on that thread? Sorry for the mess!
=> fix Windows path support in utils.lua

lua/scnvim/sclang.lua
=> Be able to call sclang.stop from user cmd
